### ISSUE TITLE
Refactor BlackjackGui.java

### ISSUE THREAD

**Issue by ericpalyan** [UCSB-CS56-Projects/cs56-games-blackjack#13]
A lot of the code could be factored out, placed as helper methods, organized and commented, etc. Currently there is a lot of jumbled code which can be cleaned up for efficiency and clarity of code.

~estimated 250

**Comment by arda-** [comment]
There are some cosmetic issues that can also be solved when refactoring the GUI code:

* remove hit or stay buttons after game ends
* when dealer’s cards come in in 2+ player mode, it causes the location of the buttons at to move to the left
* find more elegant way to start new game without closing and opening new window
* add OS menu option or GUI option to change game settings (players, bet) without running the app again
 
(separate from the the 300 points above) 50 points per item, total 200 points.

**Comment by tmliew** [comment]
Removed hi and stay button after game ends, Added OS Menu to change player names, exit, restart, etc. Refactored the code that creates a new Name Frame that specifies the names of each player.

**Comment by arda-** [comment]
fixed
