### ISSUE TITLE
Add Game Statistics

### ISSUE THREAD

**Issue by ericpalyan** [UCSB-CS56-Projects/cs56-games-blackjack#14]
~depends #8 
What is a game without keeping score? Enhance the game by keeping track of statistics such as each player's: wins, losses, money made/lost, etc. and displaying the updated stats at the end of each round.

~estimated 200

**Comment by JaredBJensen** [comment]
Done. The game now keeps track of a player's wins, losses, money won and money lost and displays these stats below their money.
