### ISSUE TITLE
Add Save/Load feature

### ISSUE THREAD

**Issue by ericpalyan** [UCSB-CS56-Projects/cs56-games-blackjack#15]
~depends #14 

Allow the user(s) to save their statistics such as wins/losses/money/etc. so that they can return another time and load their data and continue on from there adding to their current statistics. Since most of the data should be primitives, consider simply outputting to a raw text file for the save and an algorithm to read back the data from the file as the load method.

~estimated: 250

**Comment by JaredBJensen** [comment]
Done. The game will save and load stats based on the name a player provides. So if a player named "player1" saves their stats at the end of a round (this is when the save stats button appears) their stats will be written to "player1.txt" 
Then, to load these stats one would have to put player1 as their name the next time around and select the "load saved stats" check box below the name input boxes. Then the game will load from "player1.txt" and restore their saved stats.

**Comment by SElegans** [comment]
F16 CLOSED: finished issue
