### ISSUE TITLE
Allow player(s) to back out of the game

### ISSUE THREAD

**Issue by ericpalyan** [UCSB-CS56-Projects/cs56-games-blackjack#16]
If playing with multiple players, there should be an option for a player to quit/back out of the game without having to exit the entire program and then select less amount of players, set it up, etc. This should remove the player's jpanel and components from the Blackjack window and update the game instances such as number of players, and so on.

~estimated 200

**Comment by JaredBJensen** [comment]
Done. At the end of each round a "leave game" button appears below each player. If the last player leaves the game will close.

**Comment by tmliew** [comment]
Not all buttons work, specifically only the West button actually exits the game.
