### ISSUE TITLE
GUI / windowing improvements

### ISSUE THREAD

**Issue by arda-** [UCSB-CS56-Projects/cs56-games-blackjack#22]
There are some cosmetic issues that can also be solved when refactoring the GUI code:

- remove hit or stay buttons after game ends - 50 pts
- when dealer’s cards come in in 2+ player mode, it causes the location of the buttons at to move to the left - 50 pts
- find more elegant way to start new game without closing and opening new window - 50 pts
- add OS menu option or GUI option to change game settings (players, bet) without running the app again - 150 pts

Total possible 300 points

**Comment by arda-** [comment]
consolidating into issue #13

**Comment by arda-** [comment]
Reopened for clarity: refactoring the GUI code is related but a separate issue from fixing GUI issues.

**Comment by tmliew** [comment]
OS Menu now allows you to restart a game without closing and opening a new window, menus added to the top of the game, hit and stay buttons removed at round end.

**Comment by arda-** [comment]
All features fixed or implemented, except:
> find more elegant way to start new game without closing and opening new window - 50 pts
Which has now been moved to a new issue: #38
