### ISSUE TITLE
Negative betting allowed

### ISSUE THREAD

**Issue by tmliew** [ucsb-cs56-projects/cs56-games-blackjack#24]
When betting there is no limit for any player to bet, allowing anyone to go into the negatives. It should end when one has no money left.

**Comment by arda-** [comment]
approved, 50 points.

**Comment by tmliew** [comment]
Fixed, now a player can't go past $0.

**Comment by arda-** [comment]
Is this issue valid once again now that adding money is allowed?

**Comment by SElegans** [comment]
F16 OK (50 pts)
