### ISSUE TITLE
Add Sounds

### ISSUE THREAD

**Issue by tmliew** [UCSB-CS56-Projects/cs56-games-blackjack#27]
Such as cards being flipped, dealing the cards, background music.

**Comment by tmliew** [comment]
Added background music, just need audio files for the cards being flipped/dealt and it's good.

**Comment by arda-** [comment]
Issue approved, 200 points.

**Comment by arda-** [comment]
75 points of work left over from tmliew and john-lau's submission for the CARD SOUND component of this issues. (see w16_lab10.md file)

W16 OK

**Comment by arda-** [comment]
Music has been added - issue resolved.
Moving card flipping to new issue: #37
