### ISSUE TITLE
Allow all bet amounts instead of just set amounts

### ISSUE THREAD

**Issue by tmliew** [UCSB-CS56-Projects/cs56-games-blackjack#28]
Instead of just $50, $100, $150, $250, allow the player to add them. For example, clicking $50 twice would make the bet amount $100.

**Comment by tmliew** [comment]
Done, players now have more options and can add up their bets to bet higher amounts

**Comment by arda-** [comment]
Issue Approved – 50 points.

**Comment by arda-** [comment]
feature added
