### ISSUE TITLE
Incorporate user's custom bet amounts into the GUI

### ISSUE THREAD

**Issue by arda-** [ucsb-cs56-projects/cs56-games-blackjack#32]
"Learning" the user's preferred bet amounts and replacing the GUI option with custom amounts specified by the user – 200 points

requires completion of Issue #31.

**Comment by SElegans** [comment]
F16 OK (300 pts)

**Comment by chavez95** [comment]
The spilt button comes up when player does not meet the qualifications to split the hand. In the picture below the player does not have for of same value but the split button is available.

![rickdoesnothavesamedenominationcards](https://cloud.githubusercontent.com/assets/22176497/20048000/1c3d7b4e-a46e-11e6-9335-b93ad1c3d483.png)
