### ISSUE TITLE
User can press press the split button after he/she has pressed the hit button

### ISSUE THREAD

**Issue by chavez95** [UCSB-CS56-Projects/cs56-games-blackjack#49]
The user should only have the option to split their hand before they press the hit button.

**Comment by chavez95** [comment]
Also if there is an illegal combination Jack, Queen, King, or 10 the split button is shown. From the rules I read online this should not be allowed.
@SElegans

**Comment by SElegans** [comment]
F16 OK (100 pts)

**Comment by SElegans** [comment]
F16 RESOLVED
