### ISSUE TITLE
Incorrect endgame messages

### ISSUE THREAD

**Issue by davidtsu** [UCSB-CS56-Projects/cs56-games-blackjack#52]
It is possible that the game can end with the text displaying "Dealer's Turn" when the dealer busts, rather than with the corresponding player winners. Additionally, winning players are not announced.

**Comment by davidtsu** [comment]
Also, if the last player to play a card busts, the game will read "(player) hit!" rather than the correct winners.

**Comment by SElegans** [comment]
F16 OK (200 pts)

**Comment by SElegans** [comment]
F16 RESOLVED
