### ISSUE TITLE
Closing the betting frame by pressing the 'X' button exits the game.

### ISSUE THREAD

**Issue by chavez95** [UCSB-CS56-Projects/cs56-games-blackjack#53]
At the end of a round, if a player presses 'Change Bet Amount' button, but decides he/she doesn't want to change their bet and press the 'X' on the right top corner. The game exits instead of returning to the End of round frame. @SElegans

**Comment by SElegans** [comment]
F16 OK (100 pts)

**Comment by SElegans** [comment]
F16 RESOLVED
